### ISSUE TITLE
Variable highlighter for Reactive Programming people

### ISSUE THREAD

**Issue by atomrc** [Delapouite/kakoune-ecmascript#1]
I don't really get the point of the variable highlighter. It's defined as follow:

`add-highlighter -group /ecmascript/code regex \$\w* 0:variable`

The thing is, it expect to have a `$` before the name of a variable as if we where coding some `php`. This comes from the initial `javascript.kak` file but I don't really get it.

It's a problem for people that do Reactive Programming because one of our convention is to add a `$` add the end of our "Stream" variable. `const event$ = Observable.of("...")` and only the trailing `$` get colored.

Detecting variables in javascript code is not trivial so I guess not highlighting anything is better than highlighting anything that comes after a `$` ... maybe?

What do you think?

**Comment by Delapouite** [comment]
Yes you're right. As an Angular.js people I asked myself the same question many times when `$q` or `$onDestroy` were in a different color than the rest.
I guess this exception was introduced by the jQuery people.

Thanks for the reminder.

**Comment by atomrc** [comment]
I took the liberty of removing it in my typescript.kak file :)
